# gyro_controller_config.yaml

network:
  ip_address: "0.0.0.0"
  port: 5000

# Pins pour le contrôle du bandeau LED
pins:
  data_pin: 18
  clock_pin: 23

led:
  led_count: 14          # Nombre de LEDs sur la bande

auto_update: false       # Paramètre pour activer/désactiver la mise à jour automatique

# Couleurs de l'interface
interface:
  background_color: "#2c3e50"
  section_color: "#3b5998"
  text_color: "#ecf0f1"
  button_color: "#3498db"
  button_hover_color: "#2980b9"
